#!/bin/bash

#$1 = '$file_name'
#$2 = '${file_base_name}'

##################A projekt paraméterei:################
fordito="g++"
projectfileok="main.cpp Lua-Adapter/lua_adapter.cpp"
parameterek="-std=c++14 -I lua5.3.4/include -L lua5.3.4/lib -I Lua-Adapter -lm -llua -ldl"
nev="main.run"
futtatas=true
########################################################



################Fordítás és futtatás:###################
if [[ ! -d "bin" ]]; then
	mkdir "bin"
fi

nev="bin/$nev"

if [ -f $nev ]; then ## Biztonsági mentés
    mv $nev $nev".bak";
fi

$fordito $projectfileok $parameterek "-o" $nev

if [[ $futtatas && -f $nev ]]; then
	timeout 4s gnome-terminal -x $nev;
fi
########################################################
read -p "Nyomj ENTER-t a folytatashoz!"